build:
	docker build -t zopyx/pp-server-speedata-princexml-weasyprint .

build-clean:
	docker build --no-cache -t zopyx/pp-server-speedata-princexml-weasyprint .

push:
	docker push zopyx/pp-server-speedata-princexml-weasyprint 
