[converters.prince]
cmd = "prince"
version = "prince --version"
convert = "prince {cmd_options} -v \"{source_html}\" -o \"{target_filename}\""

[converters.pdfreactor-legacy]
cmd = "pdfreactor.py"
version = "pdfreactor.py --version"
convert = "pdfreactor.py {cmd_options} --addLinks --addBookmarks --logLevel debug -i \"{source_html}\" -o \"{target_filename}\""
convert_docker = "pdfreactor.py {cmd_options} --addLinks --addBookmarks --logLevel debug -i \"{source_docker_html}\" -o \"{target_filename}\""

[converters.pdfreactor]
cmd = "pdfreactor.py"
version = "pdfreactor.py --version"
convert = "pdfreactor.py {cmd_options} --log-level DEBUG -v -i \"{source_html}\" -o \"{target_filename}\" --base-url \"{base_url}\""
convert_docker = "pdfreactor.py {cmd_options} --log-level DEBUG -v -i \"{source_docker_html}\" -o \"{target_filename}\""

[converters.antennahouse]
cmd = "run.sh"
version = "run.sh -v"
convert = "run.sh {cmd_options} -d \"{source_html}\" -o \"{target_filename}\""

[converters.weasyprint]
cmd = "weasyprint"
version = "weasyprint --version"
convert = "weasyprint {cmd_options} \"{source_html}\" \"{target_filename}\""

[converters.typesetsh]
cmd = "typeset.sh.phar"
version = "typeset.sh.phar --version"
convert = "typeset.sh.phar -vv render:html --allow-local / -rx \"{source_html}\" \"{target_filename}\""

[converters.pagedjs]
cmd = "pagedjs-cli"
version = "pagedjs-cli --version"
convert = "pagedjs-cli -t 10000 \"{source_html}\" -o \"{target_filename}\""

[converters.wkhtmltopdf]
cmd = "wkhtmltopdf"
version = "wkhtmltopdf --version"
convert = "wkhtmltopdf {cmd_options} \"{source_html}\" \"{target_filename}\""

[converters.speedata]
cmd = "sp"
version = "sp --version"
convert = "sp --jobname out --timeout 30 --runs 2 --wd \"{work_dir}\" --outputdir \"{work_dir}/out\" {cmd_options}"

[converters.calibre]
cmd = "ebook-convert"
version = "ebook-convert --version"
convert = "ebook-convert \"{source_html}\" \"{target_filename}\" {cmd_options}"

[converters.vivliostyle]
cmd = "vivliostyle"
version = "vivliostyle --version"
convert = "vivliostyle build --output \"{target_filename}\" \"{source_html}\""

[converters.versatype]
cmd = "versatype-formatter"
version = "versatype-formatter --version"
convert = "versatype-formatter \"{source_html}\" --output \"{target_filename}\" \"{cmd_options}\""
